on:
  push:
    branches:
      - main

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dependencies
      run: |
        echo `python3 --version`
        sudo apt-get install -y python-setuptools
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools
        python3 -m pip install torch
        python3 -m pip install -e git+https://github.com/facebookresearch/detectron2.git#egg=detectron2
        python3 -m pip install -e git+https://github.com/facebookresearch/mobile-vision.git#egg=mobile_cv
        python3 -m pip install .
      id: build
    - name: Build the docset
      run: | 
        cd ./docs
        pip install -r requirements.txt
        make html 
        cd ..    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/build/html # The folder the action should deploy. 
